[build]
  command = "npm run build"
  publish = "web-build"
  base = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  EXPO_USE_DEV_SERVER = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 